### ISSUE TITLE
Maintenance status of this repository?

### ISSUE THREAD

**Issue by rockywarren-vertex** [lightbend/scala-logging#225] opened 2020-07-28 14:57 UTC
It looks like the latest version, 3.9.2, was published in Jun, 2019. I'm wanting [this fix](https://github.com/Ophirr33/scala-logging/commit/a6903f69ad71ab14d69860444735f03de64e005a) made in Aug, 2019 so I can mock `LoggerTakingImplicit` in tests. When is the next release planned? I'm happy to help if I can. Thanks!

**Comment by SethTisue** [comment] 2021-02-04 20:01
Doing #254 first, then this can go forward

**Comment by SethTisue** [comment] 2021-02-09 16:49
notable merged PRs since 3.9.2 containing user-visible changes:

* Fix for shapeless `@@` types passed on as args (#219)
* Make `LoggerTakingImplicit` no longer final (#181)

the rest is just version bumps and such

**Comment by SethTisue** [comment] 2021-02-09 17:05
* tag: https://github.com/lightbend/scala-logging/releases/tag/v3.9.3
* release job: https://travis-ci.com/github/lightbend/scala-logging/builds/216562258

hmm, `2021-02-09 17:05:09.894Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.scala-logging is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:405)`

**Comment by SethTisue** [comment] 2021-02-09 17:10
I might be able to get the rights to publish to that org, but I think this is an opportune time to change Typesafe to Lightbend everywhere.

**Comment by SethTisue** [comment] 2021-02-09 17:42
new release job: https://travis-ci.com/github/lightbend/scala-logging/builds/216566079

gah, `2021-02-09 17:36:20.845Z error [Sonatype] [MISSING_PROFILE] Profile com.lightbend is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:405)`

I thought my Sonatype account had permissions to publish to com.lightbend, but I guess not. (I have them on Bintray, maybe got that confused in my head?)

Well, I think we should go forward with the renamings regardless.

I will attempt to secure the needed permissions.

**Comment by SethTisue** [comment] 2021-02-09 17:46
Heh, it seems from https://issues.sonatype.org/browse/OSSRH-49971 that I have com.typesafe rights but not com.lightbend rights. But I guess the com.typesafe rights don't apply to com.typesafe.scalalogging? Regardless, I should get com.lightbend rights.

**Comment by SethTisue** [comment] 2021-02-09 20:10
> I think we should go forward with the renamings regardless.

After discussing this with Adriaan, he convinced me we shouldn't do that, actually. And I have now reverted #259.

The issue is that there is a tendency for Lightbend customers assume anything to assume that anything that says "lightbend" is supported. Both in the sense of commercially supported and in other, more informal senses of "supported".

But this library is now almost entirely community-maintained; no one from Lightbend is volunteering to play more than a minimal role here.

Ideally, there would be some sort of orphanage or halfway house that could be a home for libraries like this, where the original maintainers are no longer interested. I'm only vaguely aware of what exists in this space (https://adoptoposs.org?).

**Comment by SethTisue** [comment] 2021-02-09 20:20
@analytically Can I ask you how interested you are in this library?

Option 1: You could assume ownership entirely (under your personal account or under some other org), and cut all ties with Lightbend/Typesafe in the naming and publishing.

Option 2a: We could leave the repo where it is, but you would assume responsibility for releases and publishing. Adriaan thinks you may already have the needed permissions on Sonatype; do you know if that's the case? Now that my sbt-ci-release PR is merged, all it takes to publish releases is for someone with the right Sonatype permissions to set the secure environment variables at https://travis-ci.com/github/lightbend/scala-logging/settings appropriately, following the instructions in the sbt-ci-release readme. And once they're set, publishing is as simple as using the GitHub web UI to create a tag+release.

Option 2b: We could leave the repo where it is, and I would acquire publishing permissions to com.typesafe.scalalogging and take over pulling release levers as needed.

Thoughts? I'm willing to do 2b if necessary, but my level of participation would remain quite minimal.
1 or 2a makes more sense if you're interested in actually seeing this library be healthy and not just straggle along on life support.

cc @adriaanm

**Comment by analytically** [comment] 2021-02-17 04:36
I can publish a release. Easiest option.

**Comment by SethTisue** [comment] 2021-02-17 05:44
@analytically awesome! in that case we would prefer to leave everything under com.typesafe. this will minimize disruption for users, and it's also something of a signal (admittedly only a weak signal) this it isn't being actively maintained by Lightbend.

have you used sbt-ci-release before? in order to do tag-based publishing, now that #254 is merged, you'll need to go to https://travis-ci.com/github/lightbend/scala-logging/settings and add `PGP_PASSPHRASE`, `PGP_SECRET`, `SONATYPE_PASSWORD`, and `SONATYPE_USERNAME` to the Environment Variables section, as per the instructions at https://github.com/olafurpg/sbt-ci-release/blob/master/readme.md . once that's set up, doing a release is as easy as pushing a tag (either from the command line, or via the GitHub web UI at https://github.com/lightbend/scala-logging/releases/new)

**Comment by analytically** [comment] 2021-02-17 09:50
Ok I've setup the environment variables.

**Comment by SethTisue** [comment] 2021-02-17 17:30
@analytically excellent! maybe it makes the most sense to land #227 first, then tag a release?

**Comment by analytically** [comment] 2021-02-17 17:33
@SethTisue sounds good to me

**Comment by SethTisue** [comment] 2021-02-22 14:21
#227 is merged.

**Comment by SethTisue** [comment] 2021-03-15 16:21
@analytically ready to attempt a release?

**Comment by analytically** [comment] 2021-03-16 05:20
@SethTisue yes

**Comment by SethTisue** [comment] 2021-03-16 14:43
@analytically okay -- any questions for me about how to do it?

**Comment by analytically** [comment] 2021-03-16 15:49
@SethTisue anything I need to do?

**Comment by SethTisue** [comment] 2021-03-16 16:12
@analytically yes, see my remarks above at https://github.com/lightbend/scala-logging/issues/225#issuecomment-780315776

**Comment by analytically** [comment] 2021-03-16 16:14
Strange, I can't seem to create a tag via the Web UI

**Comment by SethTisue** [comment] 2021-03-16 16:16
at https://github.com/lightbend/scala-logging/settings/access I upgraded you from "write" to "maintainer", maybe that will do it? I'm guessing

**Comment by SethTisue** [comment] 2021-03-16 16:17
at https://github.com/lightbend/scala-logging/releases there should be a "Draft a new release" button

**Comment by analytically** [comment] 2021-03-16 16:20
https://github.com/lightbend/scala-logging/releases/tag/v3.9.3 ?

**Comment by SethTisue** [comment] 2021-03-16 16:22
It's building now at https://travis-ci.com/github/lightbend/scala-logging/builds/220285472

**Comment by SethTisue** [comment] 2021-03-16 16:27
```
2021-03-16 16:23:40.909Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.scala-logging is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:408)
```

**Comment by SethTisue** [comment] 2021-03-16 16:28
Looks an oversight in #258

**Comment by SethTisue** [comment] 2021-03-17 16:15
@analytically `sonatypeProfileName` defaults to the value of `organization`, which is `com.typesafe.scala-logging`. Apparently that's not right?

I reviewed the diffs at #258 and I don't see anywhere where I removed something I shouldn't have.

**Comment by SethTisue** [comment] 2021-03-17 16:16
Note that it's actually the same error message we got back in February: https://github.com/lightbend/scala-logging/issues/225#issuecomment-776091332

**Comment by tomasherman** [comment] 2021-03-19 20:44
Hello, sorry to highjack this discussion but it's related to the original topic. It seems like this library is pretty much abandoned from the discussion ... does that mean there is not going to be a dotty (/scala3) release? Thanks

**Comment by SethTisue** [comment] 2021-03-19 20:48
@tomasherman good question. I've opened https://github.com/lightbend/scala-logging/issues/269 about that specifically

**Comment by SethTisue** [comment] 2021-03-22 16:30
@analytically I have no idea what the problem is here 🤷

**Comment by analytically** [comment] 2021-03-23 09:04
@SethTisue fixed it

**Comment by SethTisue** [comment] 2021-03-23 13:49
Ah, I see #270 now.

You could push a v3.9.4 tag, or you could delete the existing v3.9.3 tag and then recreate it — either way should work for triggering publishing.

**Comment by analytically** [comment] 2021-03-23 13:54
Pushed ...

**Comment by analytically** [comment] 2021-03-23 14:12
2021-03-23 14:11:37.493Z  info [SonatypeClient] repositoryReleased: id:comtypesafe-2822, target:releases  - (SonatypeClient.scala:377)
2021-03-23 14:11:37.498Z  info [SonatypeClient] [promote] Finished successfully  - (SonatypeClient.scala:179)

**Comment by analytically** [comment] 2021-03-23 14:12
Looks like it worked!

**Comment by SethTisue** [comment] 2021-03-23 14:14
niiiiiice. as you probably know, the lag before the artifacts actually show up on Maven Central is unpredictable. monitoring https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_2.13/3.9.3/

**Comment by SethTisue** [comment] 2021-03-23 14:45
Yay, Scala 3 artifacts at https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_3.0.0-RC1/3.9.3/ 🎉

**Closed by SethTisue** 2021-03-23 14:45 UTC

**Comment by SethTisue** [comment] 2021-03-23 14:56
@analytically I added release notes to https://github.com/lightbend/scala-logging/releases/tag/v3.9.3
